version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ros2"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ğŸ³"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ğŸ› ï¸"
