services: docker
# sudo: false

language: python
python:
  - '3.6'

install:
  - 'pip install -r docker/requirements.txt'
  - 'pip install -r .travis/requirements.txt'

env:
  # ros2
  - HUB_REPO=ros   HUB_RELEASE=dashing  HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=bionic
  - HUB_REPO=ros   HUB_RELEASE=crystal  HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=bionic
  # ros
  - HUB_REPO=ros    HUB_RELEASE=melodic HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=bionic
  - HUB_REPO=ros    HUB_RELEASE=melodic HUB_OS_NAME=debian HUB_OS_CODE_NAME=stretch
  - HUB_REPO=ros    HUB_RELEASE=kinetic HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  # gazebo
  - HUB_REPO=gazebo HUB_RELEASE=10      HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=bionic
  - HUB_REPO=gazebo HUB_RELEASE=9       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=bionic
  - HUB_REPO=gazebo HUB_RELEASE=9       HUB_OS_NAME=debian HUB_OS_CODE_NAME=stretch
  - HUB_REPO=gazebo HUB_RELEASE=9       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  - HUB_REPO=gazebo HUB_RELEASE=7       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial

script: .travis/travis.py
