services: docker
# sudo: false

language: python
python:
  - '3.6'

install:
  - 'pip install -r docker/requirements.txt'
  - 'pip install -r .travis/requirements.txt'

env:
  # ros2
  - HUB_REPO=ros2   HUB_RELEASE=ardent    HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  # ros
  - HUB_REPO=ros    HUB_RELEASE=lunar   HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  - HUB_REPO=ros    HUB_RELEASE=lunar   HUB_OS_NAME=debian HUB_OS_CODE_NAME=stretch
  - HUB_REPO=ros    HUB_RELEASE=kinetic HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  - HUB_REPO=ros    HUB_RELEASE=kinetic HUB_OS_NAME=debian HUB_OS_CODE_NAME=jessie
  - HUB_REPO=ros    HUB_RELEASE=indigo  HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=trusty
  # gazebo
  - HUB_REPO=gazebo HUB_RELEASE=9       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  - HUB_REPO=gazebo HUB_RELEASE=8       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  - HUB_REPO=gazebo HUB_RELEASE=7       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=xenial
  - HUB_REPO=gazebo HUB_RELEASE=6       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=trusty
  - HUB_REPO=gazebo HUB_RELEASE=5       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=trusty
  - HUB_REPO=gazebo HUB_RELEASE=4       HUB_OS_NAME=ubuntu HUB_OS_CODE_NAME=trusty

script: .travis/travis.py
