---
name: CRON Trigger nightly images

on:
  schedule:
  # nightly packaging job usually finish around 14 UTC
  - cron:  '0 15 * * *'
  push:
    branches:
    - master
    paths:
    - '.github/workflows/trigger_nightly.yaml'
    - 'ros2/nightly/**'
jobs:
  nightly_build:
    name: Trigger nightly image
    env:
      dockerTag: ${{ 'nightly' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Call nightly webhook
      run: |
        curl -H "Content-Type: application/json" --data '{"docker_tag": "${{env.dockerTag}}"}'  -X POST ${{ secrets.DOCKER_ROS2_POST_PUSH_TRIGGER }}
